#page title
page_title                                : AURORA Clinic app                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : in                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/developer/apple/id284417353?mt=12                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps        # Enter Google Play Store URL.
presskit_download_link                    : https://abhisekde.github.io                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : AURORA Clinic app                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Clinic management and patient care for small clinics and independent practitioners. Say goodbye to paper charts and pen and paper note taking! Download AURORA on your phone or tablet and start for free.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Abhisek De                                
your_link                                 : https://abhisekde.github.io                     
your_city                                 : Kolkata - India                                
email_address                             : aurora.clinic.app@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Use on your phone or tablet
    description                           : No need to buy fancy computer or any special softwares. Just download the app on your phone or tablet. 
    fontawesome_icon_name                 : mobile
    
  - title                                 : Easily manage patients
    description                           : Create patient profiles with basic informations like name, gender and a phone number. Clinic sessions and medical records can be easily viewed for each profiles. 
    fontawesome_icon_name                 : user-injured
    
  - title                                 : All your visits
    description                           : Personally create your appointments or let your assistant do it for you. All of them will show up in your daily calendar.
    fontawesome_icon_name                 : calendar-check

  - title                                 : Digital prescriptions
    description                           : Record your clinic sessions directly on the app, no more paper charts or pen and paper note taking! Share your prescriptions directly with the patient.
    fontawesome_icon_name                 : file-prescription

  - title                                 : Less data entry 
    description                           : Use our extensive search for diseases, treatments etc. We do the data entry, you treat the patients.
    fontawesome_icon_name                 : keyboard
  
  - title                                 : Easy to use interface
    description                           : Fluid and uncluttered interface for you pleasure of use. Simple and intuitive workflows.
    fontawesome_icon_name                 : star

  - title                                 : Secure cloud storage
    description                           : All of your and your patients'' data are securely stored in the cloud. Login from any device and access your data any time.
    fontawesome_icon_name                 : cloud

  - title                                 : Dashboard and reports
    description                           : Dashboard to preview your daily progress and peek you upcoming appointment. More reports coming soon!
    fontawesome_icon_name                 : chart-line

  - title                                 : Support
    description                           : Request addition of a new drug or report a new disease to, and more. Support is just a click away.
    fontawesome_icon_name                 : info-circle


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#212237"
cover_overlay_transparency                : 0.7

device_color                              : black               # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
